version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "8080:15672"
      - "5671:5671"
      - "5672:5672"

  spring-cloud-config-server:
    image: cmel777/spring-cloud-config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: 'https://github.com/cmelvin/git-localconfig-repo'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://127.0.0.1:8761/eureka'
    restart: always

  netflix-eureka-naming-server:
    image: cmel777/netflix-eureka-naming-server
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - spring-cloud-config-server

  generic-pub-service:
    image: cmel777/generic-pub-service
    ports:
      - "8000:8000"
    environment:
      SERVER_ADDRESS: '127.0.0.1'
      SERVER_PORT: '8000'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://127.0.0.1:8761/eureka'
    restart: always
    depends_on:
      - rabbitmq
      - spring-cloud-config-server
      - netflix-eureka-naming-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  pub-service:
    image: cmel777/pub-service
    ports:
      - "7777:7777"
    environment:
      SERVER_ADDRESS: '127.0.0.1'
      SERVER_PORT: '8000'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://127.0.0.1:8761/eureka'
    restart: always
    depends_on:
      - spring-cloud-config-server
      - netflix-eureka-naming-server
      - rabbitmq
      - generic-pub-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/health"]
      interval: 30s
      timeout: 10s
      retries: 3
